services:
  loki:
    image: grafana/loki:3.0.0
    container_name: lesson83_loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:3.0.0
    container_name: lesson83_promtail
    command: -config.file=/etc/promtail/promtail.yaml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker/promtail/promtail.yaml:/etc/promtail/promtail.yaml:ro
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:11.1.0
    container_name: lesson83_grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    depends_on:
      - loki
